### ISSUE TITLE
About the PR

### ISSUE THREAD

**Issue by mgiannopoulos24** [CoutHi/mounter#1]
Hi. 

You said you messed up the PR. No worries. Unfortunately I removed the fork from my profile but we have 2 options. 

1. I make a new fork and a new PR.
2. You just make a Makefile and a new version of the mounter file but using dynamic allocation.

Let me know what you prefer.

**Comment by CoutHi** [comment]
I would like you to keep showing up as a contributer so if you want you're welcome to make a new fork. But the previous code had problems with compiling on my system and it would core dump. 

#define _POSIX_C_SOURCE 200809L
#define _GNU_SOURCE 

the above lines fix the problems with compiling but I haven't been able to locate what causes the program to core dump as of yet.
